#+TITLE: System implementation for LDS
#+AUTHOR: VLEAD
#+DATE: [2016-12-20 Thu]
#+SETUPFILE: ../../org-templates/level-2.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 



A system has clear boundaries of input, output and state.
In the context of our application, the system interacts with
the external world (through command line function calls)
and also manages the entity objects in such a way that the
system invariants are maintained. 

The system's inputs are in terms of /operations/.  Each
operation consists of an operation name and a sequence of
arguments.  

In this implementation, an operation is identified by a
class.  The dictionary =ops_table= maps operation names to
their corresponding classes.

Each operation is divided into four checks.  A /check/ is a
predicate that either returns true or throws an exception.

The following checks are performed:

  - Arity check :: checks if the operation has the right
       number  of arguments.

  - Type check :: checks if the arguments have the correct
       type. 

  - Auth check :: checks if the session performing the
       operation is authorized to do so.

  - State check :: checks if the operation meets all the
       constraints imposed by the state of the system
       (referential integrity constraints, etc.)
 

** Structure of each operation class

The class corresponding to each operation has five fields:

  - arg_types :: a list of type predicates.  The length of
       this list is the arity of the operation.  The arity
       check is simply a comparison of the length of this
       list with the length of the list of arguments.  Each
       predicate in the =arg_types= list is applied to the
       corresponding argument to check the type of that
       argument.

  - auth_check :: a function that checks if the  =args= (which
       may include a session) together satisfy the
       authorization conditions imposed by the operation. 

  - state_check :: a function that checks =args= and checks
       if the particular state invariant holds.

  - action :: a function on args that (presumably) changes
       the state of the system and also returns an answer.
       An exception thrown by this function indicates a
       serious failure in the application (e.g., out of
       memory error). 


* The =System= class
  :PROPERTIES: the_system_class
  :CUSTOM_ID: 
  :END: 
  There is only one =System= in the application.

** Constructor
  :PROPERTIES:
  :CUSTOM_ID: constructor
  :END: 

   This is the generic =System= implementation.  The entities that make up the
   sytem can be pure objects or objects that can be persisted.

   The specific tasks on the composed objects is agnostic to the =system=.
   This is achieved by defining an API that the system uses and is implemented
   by composed entity set.

   The system is initialized based on what the system should be composed of.

#+NAME: class_system
#+begin_src python
class System ():

    def __init__(self):
        raise Error('Can not instantiate')

    @staticmethod
    def initialize_system(cls):
        System.delegate = cls()

    @staticmethod
    def is_session_valid(session):
        return session.get("key") == KEY
 
#+end_src

*** Test Constructor
#+NAME: test_constructor
#+BEGIN_SRC python
class TestSystemConstructor(TestCase):
    TESTING = True

    def create_app(self):
        app = create_app(config)
        return app

    def setUp(self):
        System.initialize_system(PersistenceDelegate)

    def tearDown(self):
        System.delegate = None

    def test_delegate(self):
        print "test_delegate"
        self.assertEqual(isinstance(System.delegate, PersistenceDelegate), 
                             True)

    def test_is_session_valid(self):
        print "test_is_session_valid"
        session = Session(key=KEY)
        self.assertEqual(System.is_session_valid(session), True)

    def test_is_session_not_valid(self):
        print "test_is_session_not_valid"
        session = Session(key="jdhfkjhdakjf")
        self.assertEqual(System.is_session_valid(session), False)

#+END_SRC


** Arity and Type check methods 
  :PROPERTIES:
  :CUSTOM_ID: arity_and_type_check_methods
  :END: 
   Arity Check ensures that correct number of arguments are passed to a
   functions.  Type Check ensures that the type of the arguments passed to a
   function are same as expected.
   
   Any operation, before being executed is subjected to =Arity= and =Type=
   checks.

#+NAME: arity_type_checks
#+BEGIN_SRC python
   
    @staticmethod
    def arity_check(args, n):
       if  (len(args) != n) :
          raise ArityError("arity mismatch: size of args  does not " + 
                           "match operation arity " )

    @staticmethod
    def type_check(args, arg_types):
        for key, value in args.iteritems():
            if not arg_types[key](value):
                raise TypeError("type mismatch: argument %s is not of "
                                "type %s" % (value, key))

#+end_src

*** Test Arity and Type Checks
  #+NAME: test_arity_and_types
  #+BEGIN_SRC python
    def test_arity(self):
        print "test_arity"
        with self.assertRaises(ArityError):
            System.arity_check([1,2], 3)

    def test_type_checks(self):
        print "test_type_checks"
        args = {"lab": Session(key=KEY)}

        arg_types = {"lab": is_lab}

        with self.assertRaises(TypeError):
            System.type_check(args, arg_types)

  #+END_SRC

    
* =do= method 
  :PROPERTIES:
  :CUSTOM_ID: do_function
  :END: 
   The =do= method is the main work-horse of =System= which is construed as the
   =Controller=.  Every operation follows a template and realized as a class
   that defines:
   1. Number of Arguments
   2. Type of Arguments
   3. Who is allowed to perform the operation
   4. Referential integrity checks and finally
   5. the operation that changes state of the system. 


#+NAME: do_function
#+begin_src python
    @staticmethod   
    def do(op, **args):
        cls = ops_table[op]
        arg_types  = cls.arg_types
        auth_check = cls.auth_check
        state_check = cls.state_check
        arity_and_type_checks_needed = cls.arity_and_type_checks_needed
        try:
            if arity_and_type_checks_needed:
               System.arity_check(args.keys(), len(arg_types.keys()))
               System.type_check(args, arg_types)
            auth_check(args)
            state_check(args)
            return cls.action(args)
        except (ArityError, TypeError, NotAuthorizedError, StateError) as err:
            raise err

#+end_src


* Operations
  :PROPERTIES:
  :CUSTOM_ID: operations
  :END: 
  Operations provide the mechanism to either change or retrieve the state of
  the system.  While the system state is changed, it is imperative to maintain
  the invariant of the system.  Before the actual change in system is made,
  each operation goes through a series of checks:
  1. Arity Check - ensures the right number of arguments are provided to
     the operation.
  2. Type Check - ensures the arguments are of right type
  3. Auth Check - ensures only the authorized can perform the operation
  4. State Check - ensures System invariant is maintained

  Once these checks are satisfied, either the system state is modified or retrieved.

** =AddLab=
  :PROPERTIES:
  :CUSTOM_ID: class_add_lab
  :END: 
#+NAME: class_add_lab
#+begin_src python
class AddLab():
    arg_types = {"lab": is_lab, "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        lab = args["lab"]
        if System.delegate.lab_exists(lab):
            raise StateError("lab %s already exists in System"
                                 % lab.to_client())

    @staticmethod
    def action(args):
        lab = args["lab"]
        lab = System.delegate.add_lab(lab)
        return lab

#+end_src


** =UpdateLab=
  :PROPERTIES:
  :CUSTOM_ID: class_update_lab
  :END: 
#+NAME: class_update_lab
#+begin_src python
class UpdateLab():
    arg_types = {"lab": is_lab, "lab_name": is_str_or_none,
                     "lab_id": is_str_or_none, 
                     "overview" : is_str,
                     "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        pass

    @staticmethod
    def action(args):
        lab = args["lab"]

        if not "lab_name" in args:
           lab_name=question.get("lab_name")
        else:
           lab_name=args["lab_name"]

        if not "lab_id" in args:
           lab_id = lab.get("lab_id")
        else:
           lab_id = args["lab_id"]

        if not "overview" in args:
           overview = lab.get("overview")
        else:
           overview = args["overview"]

        lab = System.delegate.update_lab(lab, lab_name,\
                                         lab_id, overview)
        return lab

#+end_src


** =DeleteLab=
  :PROPERTIES:
  :CUSTOM_ID: class_delete_lab
  :END: 
#+NAME: class_delete_lab
#+begin_src python
class DeleteLab():
    arg_types = {"l_id": is_int, "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        pass

    @staticmethod
    def action(args):
        l_id = args["l_id"]
        l_id = System.delegate.delete_lab(l_id)
        return l_id

#+end_src


** =AddExperiment=
  :PROPERTIES:
  :CUSTOM_ID: class_add_experiment
  :END: 
#+NAME: class_add_experiment
#+begin_src python
class AddExperiment():
    arg_types = {"experiment": is_experiment, "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        experiment = args["experiment"]
        if System.delegate.experiment_exists(experiment):
            raise StateError("experiment %s already exists in System"
                                 % experiment.to_client())

    @staticmethod
    def action(args):
        experiment = args["experiment"]
        experiment = System.delegate.add_experiment(experiment)
        return experiment

#+end_src



** =UpdateExperiment=
  :PROPERTIES:
  :CUSTOM_ID: class_update_experiment
  :END: 
#+NAME: class_update_experiment
#+begin_src python
class UpdateExperiment():
    arg_types = {"experiment": is_experiment, "exp_name": is_str_or_none,
                     "exp_id": is_str_or_none,
                     "overview" : is_str_or_none,
                     "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        pass

    @staticmethod
    def action(args):
        experiment = args["experiment"]
        if not "exp_name" in args:
           exp_name=experiment.get("exp_name")
        else:
           exp_name=args["exp_name"]

        if not "exp_id" in args:
           exp_id = experiment.get("exp_id")
        else:
           exp_id = args["exp_id"]
        
        if not "overview" in args:
           overview = experiment.get("overview")
        else:
           overview = args["overview"]

        exp = System.delegate.update_experiment(experiment, exp_name,\
            exp_id, overview)
        return exp

#+end_src


** =DeleteExperiment=
  :PROPERTIES:
  :CUSTOM_ID: class_delete_experiment
  :END: 
#+NAME: class_delete_experiment
#+begin_src python
class DeleteExperiment():
    arg_types = {"e_id": is_int, "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        pass

    @staticmethod
    def action(args):
        e_id = args["e_id"]
        e_id = System.delegate.delete_experiment(e_id)
        return e_id
        
#+end_src


** =DeleteSection=
  :PROPERTIES:
  :CUSTOM_ID: class_delete_section
  :END: 
#+NAME: class_delete_section
#+begin_src python
class DeleteSection():
    arg_types = {"s_id": is_int, "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        pass

    @staticmethod
    def action(args):
        s_id = args["s_id"]
        s_id = System.delegate.delete_section(s_id)
        return s_id
        
#+end_src


** =AddSection=
  :PROPERTIES:
  :CUSTOM_ID: class_add_section
  :END: 
#+NAME: class_add_section
#+begin_src python
class AddSection():
    arg_types = {"section": is_section, "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        section = args["section"]
        if System.delegate.section_exists(section):
            raise StateError("section %s already exists in System"
                                 % section.to_client())

    @staticmethod
    def action(args):
        section = args["section"]
        section = System.delegate.add_section(section)
        return section

#+end_src

   
** =UpdateSection=
  :PROPERTIES:
  :CUSTOM_ID: class_update_section
  :END: 
#+NAME: class_update_section
#+begin_src python
class UpdateSection():
    arg_types = {"section": is_section, "name": is_str_or_none,
                     "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        pass

    @staticmethod
    def action(args):
        section = args["section"]
        if not "name" in args:
           name=section.get("name")
        else:
           name=args["name"]

        section = System.delegate.update_section(section, name)
        return section

#+end_src


** =AddExperimentsToLab=
  :PROPERTIES:
  :CUSTOM_ID: class_add_experiments_to_lab
  :END: 
#+NAME: class_add_experiments_to_lab
#+begin_src python
class AddExperimentsToLab():
    arg_types = {"experiments": are_experiments, "labid": is_int, 
                     "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            current_app.logger.error("auth error raised, session = %s" % 
                                        session.to_client())
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        labid = args["labid"]
        if not System.delegate.lab_exists(labid):
            current_app.logger.error("lab with id = %d does not exist"
                                     " in System" % labid)
            raise StateError("lab with id = %d does not exist in System"
                                 % labid)

    @staticmethod
    def action(args):
        labid = args["labid"]
        experiments = args["experiments"]
        try:
            lab = System.delegate.add_experiments_to_lab(labid, experiments) 
            return lab
        except Exception as err:
            current_app.logger.error("Exception = %s" % str(err))
            raise err

#+end_src



** =AddSectionsToExperiment=
  :PROPERTIES:
  :CUSTOM_ID: class_add_sections_to_experiment
  :END: 
#+NAME: class_add_sections_to_experiment
#+begin_src python
class AddSectionsToExperiment():
    arg_types = {"sections": are_sections, "expid": is_int, 
                     "session": is_session}
    arity_and_type_checks_needed = True

    @staticmethod
    def auth_check(args):
        session = args['session']
        if not System.is_session_valid(session):
            current_app.logger.error("auth error raised, session = %s" % 
                                        session.to_client())
            raise NotAuthorizedError("Not Authorized to perform this action")

    @staticmethod
    def state_check(args):
        expid = args["expid"]
        if not System.delegate.experiment_exists(expid):
            current_app.logger.error("exp with id = %d does not exist"
                                     " in System" % expid)
            raise StateError("lab with id = %d does not exist in System"
                                 % labid)

    @staticmethod
    def action(args):
        expid = args["expid"]
        sections = args["sections"]
        try:
            exp = System.delegate.add_sections_to_experiment(expid, sections) 
            return exp
        except Exception as err:
            current_app.logger.error("Exception = %s" % str(err))
            raise err

#+end_src


** Operations Table
  :PROPERTIES:
  :CUSTOM_ID: ops_table
  :END: 
   Each operation has a corresponding implementation defined as a class.

 #+NAME: ops_table
 #+BEGIN_SRC python                                                                          
ops_table = {'add_lab' : AddLab,
             'update_lab': UpdateLab,
             'delete_lab': DeleteLab,
             'add_experiment' : AddExperiment,
             'update_experiment' : UpdateExperiment,
             'delete_experiment' : DeleteExperiment,
             'add_experiments_to_lab' : AddExperimentsToLab,
             'add_section' : AddSection,
             'update_section' : UpdateSection,
             'delete_section' : DeleteSection
             }

 #+END_SRC   

    
* Infra                                                         :boilerplate:

** sources
*** Imports 
#+name: imports_for_sources
#+BEGIN_SRC python
# -*- coding: utf-8 -*-

from runtime.exceptions.custom_exceptions import *
from runtime.objects.entities import is_str, is_lab,\
     is_date, is_session, is_section, is_int, is_experiment,\
     are_experiments
from runtime.utils.type_utils import is_str_or_none
from runtime.config.system_config import KEY
from runtime.config.feedback_forms import feedback_forms
import datetime
from flask import current_app

#+end_src


** tests
*** Imports 
#+name: imports_for_tests
#+BEGIN_SRC python
# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-
import unittest
from flask_testing import TestCase
from runtime.rest.app import create_app
from runtime.system.system import *
from runtime.system.persistence_delegate import *

config = {
         'SQLALCHEMY_DATABASE_URI': ''
         }

#+end_src

*** Running tests
#+NAME: run_test_cases
#+BEGIN_SRC python
if __name__ == '__main__':
    unittest.main()

#+END_SRC


* Tangling                                                      :boilerplate:

** sources
#+BEGIN_SRC python :tangle system.py :eval no :noweb yes
<<imports_for_sources>>
<<class_system>>
<<arity_type_checks>>
<<do_function>>
<<class_add_lab>>
<<class_delete_lab>>
<<class_delete_section>>
<<class_update_section>>
<<class_delete_experiment>>
<<class_update_lab>>
<<class_add_experiment>>
<<class_update_experiment>>
<<class_update_section>>
<<class_add_experiments_to_lab>>
<<class_add_section>>
<<ops_table>>

#+end_src


** tests
#+BEGIN_SRC python :tangle test_system.py :eval no :noweb yes
<<imports_for_tests>>
<<test_constructor>>
<<test_arity_and_types>>
<<run_test_cases>>
#+end_src
