#+TITLE: Data Model for Lab Data Service
#+AUTHOR: VLEAD
#+DATE: [2016-11-30 Wed]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  The application or the system is abstracted as the data model.  The model
  captures: the entities that comprise the system; relations and constraints
  between these entities; and operations that entail a change in the state of
  the system.

  The purpose of this document is to describe the expected behaviour of the lab
  data service. It is a specification for the requirements of this service.

  
* Notation
  :PROPERTIES:
  :CUSTOM_ID: notation
  :END: 
  The system is defined as the data model.  There is a certain notation that is
  used for defining the data model. 

** Sets, cardinality and relations
  :PROPERTIES:
  :CUSTOM_ID: sets_cardinality_and_relations
  :END: 

If =A= is a set, then
    1. =A!= denotes exactly one element of =A=.
    2. =A?= denotes at most one element of =A=.
    3. =A+= denotes  one or more elements of =A=
    4. =A*=  denotes at zero or more elements of =A=.  Often
       abbreviated as =A=.

    5. =A > B= denotes a relation /from/ =A= /to/ =B=.

** Relations and their cardinality type
  :PROPERTIES:
  :CUSTOM_ID: relations_and_their_cardinality_type
  :END: 

A relation =r:A > B= could relate each element of =A= to
zero, one or more elements of =B=.

|--------------------------------+-----------|
| Cardinality of B               | Notation  |
|--------------------------------+-----------|
| at least zero elements of =B=. | r: A > B  |
|--------------------------------+-----------|
| at most one element of =B=     | r: A > B? |
|--------------------------------+-----------|
| at least one element of =B=    | r: A > B+ |
|--------------------------------+-----------|
| exactly one element of =B=     | r: A > B! |
|--------------------------------+-----------|
   


* Informal abstraction of the data model
  :PROPERTIES:
  :CUSTOM_ID: informal_abstraction_of_the_data_model
  :END: 
** Abstract Entity Types
  :PROPERTIES:
  :CUSTOM_ID: abstract_entity_types
  :END: 
  The following are the abstract data types in our system.
*** Lab
:PROPERTIES:
:CUSTOM_ID: entity_lab
:END: 
  Requirement satisfied: [[../requirements/index.org::#lab][Lab]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Lab
#+END_SRC
 
*** Experiment
:PROPERTIES:
:CUSTOM_ID: entity_experiment
:END: 
  Requirement satisfied: [[../requirements/index.org::#experiment][Experiment]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Experiment
#+END_SRC

*** Institute
:PROPERTIES:
:CUSTOM_ID: entity_institute
:END: 
  Requirement satisfied: [[../requirements/index.org::#institute][Institute]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Institute
#+END_SRC

*** Discipline
:PROPERTIES:
:CUSTOM_ID: entity_discipline
:END: 
  Requirement satisfied: [[../requirements/index.org::#discipline][Discipline]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Discipline
#+END_SRC

*** Developer
:PROPERTIES:
:CUSTOM_ID: entity_developer
:END: 
  Requirement satisfied: [[../requirements/index.org::#developer][Developer]]

#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Developer
#+END_SRC

*** Section
:PROPERTIES:
:CUSTOM_ID: entity_section
:END: 
  Requirement satisfied: [[../requirements/index.org::#section][Section]]

#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Section
#+END_SRC

*** Name
:PROPERTIES:
:CUSTOM_ID: entity_name
:END: 
  Requirement satisfied: [[../requirements/index.org::#name][Name]]

#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Name
#+END_SRC

*** Email
:PROPERTIES:
:CUSTOM_ID: entity_email
:END: 
  Requirement satisfied: [[../requirements/index.org::#email][Email]]

#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Email
#+END_SRC


* Relations and cardinality constraints over entity types 
  :PROPERTIES:
  :CUSTOM_ID: cardinal_constraints
  :END: 
  The constraints are defined both in terms of formal notation and also in
  diagrams for visual clarity. 

** Relations
  :PROPERTIES:
  :CUSTOM_ID: relations
  :END: 
   For each relation, we define its inverse next to it.
#+BEGIN_SRC spec :tangle spec.txt

;;; Relations with cardinality constraints

[developer, lab]          : Developer +  > Lab +
[discipline, lab]         : Discipline +  > Lab +
[institute, lab]          : Institute !  > Lab +
[experiment, lab]         : Experiment +  > Lab !
[experiment, section]     : Experiment > Section
[lab, name]               : Lab + > Name !
[experiment name]         : Experiment + > Name !
[institute, name]         : Institute ! > Name !
[discipline, name]        : Discipline ! > Name !
[developer, name]         : Developer + > Name !
[developer, email]        : Developer ! > Email !

#+END_SRC


** Diagrams
  :PROPERTIES:
  :CUSTOM_ID: diagrams
  :END: 
   The following diagram summarizes all the cardinality constraints across all
   entities.

#+BEGIN_HTML
<img src="https://docs.google.com/drawings/d/e/2PACX-1vQX1QRUkVjjW4hjHaUowOevT6_boqdslQfR0_awXAZmLPSx_UL8Qh_P5fYDoiCCm-IXzPX8LHs2pvId/pub?w=960&h=720">
<p align="center"> Lab Data Service Model </p>

#+END_HTML
  To edit the Lab Data Service Model image click [[https://docs.google.com/a/vlabs.ac.in/drawings/d/1Pc5ywXvy3RC4lws4KwBiv_qpukm_Fz6JPH4wh_CYjMo/edit?usp=sharing][here]]


* Keys
  :PROPERTIES:
  :CUSTOM_ID: key
  :END: 

An entity =K= is called a /key for/ an entity =A= if there
is a relation =r: A? > K!=.

|----+------------+--------|
|    | Entity     | Key    |
|----+------------+--------|
| 1. | Institute  | Name   |
|----+------------+--------|
| 2. | Discipline | Name   |
|----+------------+--------|
| 3. | Developer  | Email  |
|----+------------+--------|


* Assumptions


* System state
  :PROPERTIES:
  :CUSTOM_ID: system_state
  :END: 
  The system's state is captured by a set of /state variables/.
  
** Primary Entity sets
:PROPERTIES:
:CUSTOM_ID: primary_entity_sets
:END:    
#+BEGIN_SRC spec :tangle spec.txt
;;; Primary state variables
Sets
  lab-set  : set[Lab]  ; set of all labs in the system

 #+END_SRC


** Derived Entity sets
:PROPERTIES:
:CUSTOM_ID: derived_entity_sets
:END: 
#+BEGIN_SRC spec :tangle spec.txt
  experiment-set  : lab-set.experiment         ; set of experiments in the system
  institute-set   : lab-set.institute          ; set of institutes in the system
  discipline-set  : lab-set.discipline         ; set of disciplines in the system
  developer-set   : lab-set.developer          ; set of developers in the system

  name-set        : developer-set.name         ; set of all names of developers in the system
  email-set       : developer-set.email        ; set of all emails of developers in the system
  lab-name-set    : lab-set.lab_name           ; set of all lab-names in the system
  lab-id-set      : lab-set.lab_id             ; set of all lab_ids in the system
  exp-name-set    : exp-set.exp_name           ; set of all exp-names in the system
  exp-id-set      : exp-set.exp_id             ; set of all exp_ids in the system
  inst-name-set   : inst-set.inst_name         ; set of all inst-names in the system
  inst-id-set     : inst-set.inst_id           ; set of all inst_ids in the system
  disc-name-set   : disc-set.disc_name         ; set of all disc-names in the system
  disc-id-set     : disc-set.disc_id           ; set of all disc_ids in the system

#+END_SRC


* Referential Integrity over primary and derived entity sets
:PROPERTIES:
:CUSTOM_ID: referential_integrity_relations
:END: 
#+BEGIN_SRC spec :tangle spec.txt
[disciplines, institutes]   :  institute-set +  > discipline-set +  
[developers, institutes]    :  institute-set ! > developer-set +      
[developers, labs]          :  lab-set + > developer-set + 
[experiments, labs]         :  lab-set ! > experiment-set +

#+END_SRC


* Operations 
  :PROPERTIES:
  :CUSTOM_ID: operations
  :END: 

CRUD operations.  

Each operation is performed on an entity instance or an
entity-set.   The operation may take additional parameters.

 - C  create a user      
 - R  read from a user   
 - U  update a user      
 - D  delete a user      

** Add Lab
  :PROPERTIES:
  :CUSTOM_ID: add_lab
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l: Lab, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l: ~lab-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l = new lab
    lab-set = lab-set U {l}
#+END_SRC   



** Add Experiment
  :PROPERTIES:
  :CUSTOM_ID: add_experiment
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: Experimet, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referentials_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: ~experiment-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e = new experiment
    experiment-set = experiment-set U {e}
#+END_SRC   


** Add Institute
  :PROPERTIES:
  :CUSTOM_ID: add_institure
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i: Institute, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i: ~institute-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i = new institute
    institute-set = institute-set U {i}
#+END_SRC   



** Add Discipline
  :PROPERTIES:
  :CUSTOM_ID: add_discipline
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d: Discipline, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d: ~discipline-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d = new discipline
    discipline-set = discipline-set U {d}
#+END_SRC


** Add Developer
  :PROPERTIES:
  :CUSTOM_ID: add_developer
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r: Developer, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r: ~developer-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r = new developer
    developer-set = developer-set U {r}
#+END_SRC 


** Update Lab
  :PROPERTIES:
  :CUSTOM_ID: update_lab
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: lab_name, lid: lab_id, l: Lab, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l : lab-set
    s : session-set
    n : lab-name-set
    lid: ~lab-id-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The lab details are updated.
#+END_SRC


** Update Experiment
  :PROPERTIES:
  :CUSTOM_ID: update_experiment
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: exp_name, eid: exp_id, e: Experiment, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e : experiment-set
    s : session-set
    n : ~exp-name-set
   eid: ~exp-id-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The experiment details are updated.
#+END_SRC


** Update Institute
  :PROPERTIES:
  :CUSTOM_ID:  update_institute
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: inst_name, iid: inst_id, i: Institute, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i : institute-set
    s : session-set
    n : inst-name-set
   iid: ~inst-id-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The institute details are updated.
#+END_SRC


** Update Discipline
  :PROPERTIES:
  :CUSTOM_ID: update_discipline
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: disc_name, did: disc_id, d: Discipline, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d : discipline-set
    s : session-set
    n : disc-name-set
   did: ~disc-id-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The discipline details are updated.
#+END_SRC


** Update Developer
  :PROPERTIES:
  :CUSTOM_ID: update_developer
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: name, e: email_id, r: Developer, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r : developer-set
    n : name-set
    e :~email-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The developer details are updated.

#+END_SRC


** Delete Lab
  :PROPERTIES:
  :CUSTOM_ID: delete_lab
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l: Lab, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l : lab-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    lab-set = lab-set - {l}

#+END_SRC


** Delete Experiment
  :PROPERTIES:
  :CUSTOM_ID: delete_experiment
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: Experiment, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e : experiment-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    experiment-set = experiment-set - {e}

#+END_SRC


** Delete Institute
  :PROPERTIES:
  :CUSTOM_ID: delete_institure
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i: Institute, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i : institute-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    institute-set = institute-set - {i}

#+END_SRC


** Delete Discipline 
  :PROPERTIES:
  :CUSTOM_ID: delete_discipline
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d: Discipline, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d : discipline-set
    s : session-set
#+END_SRC   

*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    discipline-set = discipline-set - {d}

#+END_SRC


** Delete Developer
  :PROPERTIES:
  :CUSTOM_ID: delete_developer
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r: Developer, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r : developer-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    developer-set = developer-set - {r}
#+END_SRC
