#+TITLE: Data Model for Lab Data Service
#+AUTHOR: VLEAD
#+DATE: [2016-11-30 Wed]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  The application or the system is abstracted as the data model.  The model
  captures: the entities that comprise the system; relations and constraints
  between these entities; and operations that entail a change in the state of
  the system.

  The purpose of this document is to describe the expected behaviour of the lab
  data service. It is a specification for the requirements of this service.

  
* Notation
  :PROPERTIES:
  :CUSTOM_ID: notation
  :END: 
  The system is defined as the data model.  There is a certain notation that is
  used for defining the data model. 

** Sets, cardinality and relations
  :PROPERTIES:
  :CUSTOM_ID: sets_cardinality_and_relations
  :END: 

If =A= is a set, then
    1. =A!= denotes exactly one element of =A=.
    2. =A?= denotes at most one element of =A=.
    3. =A+= denotes  one or more elements of =A=
    4. =A*=  denotes at zero or more elements of =A=.  Often
       abbreviated as =A=.

    5. =A > B= denotes a relation /from/ =A= /to/ =B=.

** Relations and their cardinality type
  :PROPERTIES:
  :CUSTOM_ID: relations_and_their_cardinality_type
  :END: 

A relation =r:A > B= could relate each element of =A= to
zero, one or more elements of =B=.

|--------------------------------+-----------|
| Cardinality of B               | Notation  |
|--------------------------------+-----------|
| at least zero elements of =B=. | r: A > B  |
|--------------------------------+-----------|
| at most one element of =B=     | r: A > B? |
|--------------------------------+-----------|
| at least one element of =B=    | r: A > B+ |
|--------------------------------+-----------|
| exactly one element of =B=     | r: A > B! |
|--------------------------------+-----------|
   


* Informal abstraction of the data model
  :PROPERTIES:
  :CUSTOM_ID: informal_abstraction_of_the_data_model
  :END: 
** Abstract Entity Types
  :PROPERTIES:
  :CUSTOM_ID: abstract_entity_types
  :END: 
  The following are the abstract data types in our system.
*** Lab
:PROPERTIES:
:CUSTOM_ID: entity_lab
:END: 
  Requirement satisfied: [[../requirements/index.org::#req1][Lab]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Lab
#+END_SRC
 
*** Experiment
:PROPERTIES:
:CUSTOM_ID: entity_experiment
:END: 
  Requirement satisfied: [[../requirements/index.org::#req1][Experiment]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Experiment
#+END_SRC

*** Institute
:PROPERTIES:
:CUSTOM_ID: entity_institute
:END: 
  Requirement satisfied: [[../requirements/index.org::#req1][Institute]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Institute
#+END_SRC

*** Discipline
:PROPERTIES:
:CUSTOM_ID: entity_discipline
:END: 
  Requirement satisfied: [[../requirements/index.org::#req1][Discipline]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Discipline
#+END_SRC

*** Developer
:PROPERTIES:
:CUSTOM_ID: entity_developer
:END: 
  Requirement satisfied: [[../requirements/index.org::#req1][Developer]]

#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Developer
#+END_SRC

*** Section
:PROPERTIES:
:CUSTOM_ID: entity_section
:END: 
  Requirement satisfied: [[../requirements/index.org::#req4][Section]]

#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Section
#+END_SRC

*** Name
:PROPERTIES:
:CUSTOM_ID: entity_name
:END: 
  Requirement satisfied: [[../requirements/index.org::#req1][Name]]

#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Name
#+END_SRC

*** Email
:PROPERTIES:
:CUSTOM_ID: entity_email
:END: 
  Requirement satisfied: [[../requirements/index.org::#req1][Email]]

#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Email
#+END_SRC

*** HostingInfo
:PROPERTIES:
:CUSTOM_ID: entity_HostingInfo
:END: 
  Requirement satisfied: [[../requirements/index.org::#req6][HostingInfo]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE HostingInfo
#+END_SRC

*** Asset
:PROPERTIES:
:CUSTOM_ID: entity_Asset
:END: 
  Requirement satisfied: [[../requirements/index.org::#req7][Asset]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE Asset
#+END_SRC

*** IntegrationStatus
:PROPERTIES:
:CUSTOM_ID: entity_Integration_Status
:END: 
  Requirement satisfied: [[../requirements/index.org::#req8][IntegrationStatus]]
#+BEGIN_SRC spec :tangle spec.txt
;;; Entity Types
TYPE IntegrationStatus
#+END_SRC


* Relations and cardinality constraints over entity types 
  :PROPERTIES:
  :CUSTOM_ID: cardinal_constraints
  :END: 
  The constraints are defined both in terms of formal notation and also in
  diagrams for visual clarity. 

** Relations
  :PROPERTIES:
  :CUSTOM_ID: relations
  :END: 
   For each relation, we define its inverse next to it.
#+BEGIN_SRC spec :tangle spec.txt

;;; Relations with cardinality constraints

[developer, lab]                 : Developer +  > Lab +
[discipline, lab]                : Discipline +  > Lab +
[institute, lab]                 : Institute !  > Lab +
[experiment, lab]                : Experiment +  > Lab !
[hostinginfo, lab]               : HostingInfo + > Lab !
[asset, lab]                     : Asset + > Lab !
[integrationstatus, lab]         : IntegrationStatus ! > Lab *

[discipline, experiment]         : Discipline + > Experiment +
[institute, experiment]          : Institute ! > Experiment +
[experiment, section]            : Experiment ! > Section +
[experiment, developer]          : Experiment + > Developer +
[experiment, hostinginfo]        : Experiment ! > HostingInfo +
[asset, experiment]              : Asset + > Experiment !
[experiment, integrationstatus]  : Experiment *  > IntegrationStatus !

[developer, name]                : Developer + > Name !
[developer, email]               : Developer ! > Email !
[developer, discipline]          : Developer + > Discipline +
[developer, institute]           : Developer + > Institute !

[asset, discipline]              : Asset + > Discipline +
[asset, institute]               : Asset + > Institute !


#+END_SRC


** Diagrams
  :PROPERTIES:
  :CUSTOM_ID: diagrams
  :END: 
   The following diagram summarizes all the cardinality constraints across all
   entities.

#+BEGIN_HTML
<img src="https://docs.google.com/drawings/d/e/2PACX-1vQX1QRUkVjjW4hjHaUowOevT6_boqdslQfR0_awXAZmLPSx_UL8Qh_P5fYDoiCCm-IXzPX8LHs2pvId/pub?w=960&h=720">
<p align="center"> Lab Data Service Model </p>

#+END_HTML
  To edit the Lab Data Service Model image click [[https://docs.google.com/a/vlabs.ac.in/drawings/d/1Pc5ywXvy3RC4lws4KwBiv_qpukm_Fz6JPH4wh_CYjMo/edit?usp=sharing][here]]

#+BEGIN_HTML

<img src="https://docs.google.com/drawings/d/15lSVFck27vNzXQqCHLXpvZ-ReaLTWSsALFq40TtD3Q0/pub?w=1225&h=723">
<p align="center"> Lab Data Service Model with respect to Lab </p>

#+END_HTML
  To edit the Lab Data Service Model with respect to Lab image click [[https://docs.google.com/drawings/d/15lSVFck27vNzXQqCHLXpvZ-ReaLTWSsALFq40TtD3Q0/edit][here]]

#+BEGIN_HTML

<img src="https://docs.google.com/drawings/d/11yPJmA2dU_RmXxQNcspOh6qrtGQLf8qGLm3swfoPOlU/pub?w=1230&h=724">
<p align="center"> Lab Data Service Model with respect to Experiment </p>

#+END_HTML
  To edit the Lab Data Service Model with respect to Experiment image click [[https://docs.google.com/drawings/d/11yPJmA2dU_RmXxQNcspOh6qrtGQLf8qGLm3swfoPOlU/edit][here]]


* Keys
  :PROPERTIES:
  :CUSTOM_ID: key
  :END: 

An entity =K= is called a /key for/ an entity =A= if there
is a relation =r: A? > K!=.

|----+------------+--------|
|    | Entity     | Key    |
|----+------------+--------|
| 1. | Institute  | Name   |
|----+------------+--------|
| 2. | Discipline | Name   |
|----+------------+--------|
| 3. | Developer  | Email  |
|----+------------+--------|


* Assumptions


* System state
  :PROPERTIES:
  :CUSTOM_ID: system_state
  :END: 
  The system's state is captured by a set of /state variables/.
  
** Primary Entity sets
:PROPERTIES:
:CUSTOM_ID: primary_entity_sets
:END:    
#+BEGIN_SRC spec :tangle spec.txt
;;; Primary state variables
Sets
  lab-set  : set[Lab]  ; set of all labs in the system

 #+END_SRC


** Derived Entity sets
:PROPERTIES:
:CUSTOM_ID: derived_entity_sets
:END: 
#+BEGIN_SRC spec :tangle spec.txt
  experiment-set         : lab-set.experiment         ; set of experiments in the system
  institute-set          : lab-set.institute          ; set of institutes in the system
  discipline-set         : lab-set.discipline         ; set of disciplines in the system
  developer-set          : lab-set.developer          ; set of developers in the system
  hostinginfo-set        : lab-set.hostinginfo        ; set of hosting information in the system
  asset-set              : lab-set.asset              ; set of assets in the system
  integrationstatus-set  : lab-set.integrationstatus  ; set of integration status in the system

  name-set        : developer-set.name         ; set of all names of developers in the system
  email-set       : developer-set.email        ; set of all emails of developers in the system
  lab-name-set    : lab-set.lab_name           ; set of all lab-names in the system
  lab-id-set      : lab-set.lab_id             ; set of all lab_ids in the system
  exp-name-set    : experiment-set.exp_name    ; set of all exp-names in the system
  exp-id-set      : experiment-set.exp_id      ; set of all exp_ids in the system
  section-set     : experiment-set.section     ; set of all sections in the system
  inst-name-set   : institute-set.inst_name    ; set of all inst-names in the system
  inst-id-set     : institute-set.inst_id      ; set of all inst_ids in the system
  disc-name-set   : discipline-set.disc_name   ; set of all disc-names in the system
  disc-id-set     : discipline-set.disc_id     ; set of all disc_ids in the system
  hosting-status-set : hostinginfo-set.hosting_status ; set of all hosting_status in the system
  hosted-url-set  : hostinginfo-set.hosted_url ; set of all hosted_urls in the system
  hosted_on-set   : hostinginfo-set.hosted_on  ; set of sll hosted_on in the system
  asset-type-set  : asset-set.asset_type       ; set of all assets_types in the system
  asset-path-set  : asset-set.asset_path       ; set of all assets_paths in the system
  integration-status-set : integrationstatus-set.level ; set of all levels in the system

#+END_SRC


* Referential Integrity over primary and derived entity sets
:PROPERTIES:
:CUSTOM_ID: referential_integrity_relations
:END: 
#+BEGIN_SRC spec :tangle spec.txt

[developers, labs]                :  lab-set + > developer-set + 
[discipline, labs]                :  lab-set + > discipline-set +
[institute, labs]                 :  lab-set + > institute-set !
[experiments, labs]               :  lab-set ! > experiment-set +
[hostinginfo, labs]               :  lab-set + > hostinginfo-set +
[asset, labs]                     :  lab-set ! > asset-set +
[integrationstatus, labs]         :  lab-set * > integrationstatus-set !
[discipline, experiments]         :  experiment-set + > discipline-set +
[institute, experiments]          :  experiment-set + > institute-set !
[experiments, sections]           :  section-set + > experiment-set !
[experiments, developers]         :  developer-set + > experiment-set +
[experiments, hostinginfos]       :  hostinginfo-set + > experiment-set !
[asset, experiments]              :  experiment-set ! > asset-set +
[experiments, integrationstatus]  :  integrationstatus-set !  > experiment-set *
[developer, name]                 :  name-set ! > developer-set +
[developer, email]                :  email-set ! > developer-set !
[developer, discipline]           :  discipline-set + > developer-set +
[developers, institutes]          :  institute-set ! > developer-set + 
[asset, discipline]               :  discipline-set + > asset-set +
[asset, institute]                :  institute-set ! > asset-set +

#+END_SRC


* Operations 
  :PROPERTIES:
  :CUSTOM_ID: operations
  :END: 

CRUD operations.  

Each operation is performed on an entity instance or an
entity-set.   The operation may take additional parameters.

 - C  create a user      
 - R  read from a user   
 - U  update a user      
 - D  delete a user      

** Add Lab
  :PROPERTIES:
  :CUSTOM_ID: add_lab
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l: Lab, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l: ~lab-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l = new lab
    lab-set = lab-set U {l}
#+END_SRC   



** Add Experiment
  :PROPERTIES:
  :CUSTOM_ID: add_experiment
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: add_experiment_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: Experimet, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: add_experiment_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: add_experiment_referentials_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: ~experiment-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: add_experiment_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e = new experiment
    experiment-set = experiment-set U {e}
#+END_SRC   


** Add Institute
  :PROPERTIES:
  :CUSTOM_ID: add_institure
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: add_institute_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i: Institute, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: add_institute_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: add_institute_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i: ~institute-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: add_institute_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i = new institute
    institute-set = institute-set U {i}
#+END_SRC   



** Add Discipline
  :PROPERTIES:
  :CUSTOM_ID: add_discipline
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: add_discipline_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d: Discipline, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: add_discipline_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: add_discipline_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d: ~discipline-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: add_discipline_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d = new discipline
    discipline-set = discipline-set U {d}
#+END_SRC


** Add Section
  :PROPERTIES:
  :CUSTOM_ID: add_section
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    sec: Section, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    sec: ~section-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    sec = new section
    section-set = section-set U {sec}
#+END_SRC   



** Add Name
  :PROPERTIES:
  :CUSTOM_ID: add_name
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: Name, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l: ~lab-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n = new name
    name-set = name-set U {n}
#+END_SRC   



** Add Email
  :PROPERTIES:
  :CUSTOM_ID: add_email
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: Email, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: ~email-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e = new email
    email-set = email-set U {e}
#+END_SRC   



** Add Developer
  :PROPERTIES:
  :CUSTOM_ID: add_developer
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: add_developer_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r: Developer, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: add_developer_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: add_developer_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r: ~developer-set
#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: add_developer_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r = new developer
    developer-set = developer-set U {r}
#+END_SRC 


** Add HostingInfo
  :PROPERTIES:
  :CUSTOM_ID: add_hostinginfo
  :END:
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: add_hostinginfo_parameters
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    h: HostingInfo, s: Session
#+END_SRC
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: add_hostinginfo_actor_credentials
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: add_hostinginfo_referential_integrity
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    h : ~hostinginfo-set
#+END_SRC
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: add_hostinginfo_effect
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    h = new hostinginfo
    hostinginfo-set = hostinginfo-set U {h}
#+END_SRC



** Add Asset
:PROPERTIES:
  :CUSTOM_ID: add_asset
  :END:
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: add_asset_parameters
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    a: Asset, s: Session
#+END_SRC
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: add_asset_actor_credentials
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: add_asset_referential_integrity
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    a: ~asset-set
#+END_SRC
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: add_asset_effect
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    a = new asset    
   asset-set = asset-set U {a}
#+END_SRC


** Add IntegrationStatus
:PROPERTIES:
  :CUSTOM_ID: add_integrationstatus
  :END:
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: add_integrationstatus_parameters
  :END:
#+BEGIN_SRC spec :tangle spec.txt
   i: IntegrationStatus, s: Session
#+END_SRC
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: add_integrationstatus_actor_credentials
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: add_integrationstatus_referential_integrity
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    i: ~integrationstatus-set
#+END_SRC
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: add_integrationstatus_effect
  :END:
#+BEGIN_SRC spec :tangle spec.txt
   i = new integrationstatus
   integrationstatus-set = integrationstatus-set U {i}
#+END_SRC


** Update Lab
  :PROPERTIES:
  :CUSTOM_ID: update_lab
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: update_lab_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: lab_name, lid: lab_id, l: Lab, e: Experiment, i: Institute, d: Discipline, r: Developer, h: HostingInfo, a: Asset, is: IntegrationStatu, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: update_lab_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: update_lab_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l   : lab-set
    s   : session-set
    n   : lab-name-set
    lid : ~lab-id-set
    e   : experiment-set
    i   : institute-set
    d   : discipline-set
    r   : developer-set
    h   : hostinginfo-set
    a   : asset-set
    i   : integrationstatus-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: update_lab_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The lab details are updated.
#+END_SRC


** Update Experiment
  :PROPERTIES:
  :CUSTOM_ID: update_experiment
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: update_experiment_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: exp_name, eid: exp_id, e: Experiment, i: Institute, d: Discipline, r: Developer, h: HostingInfo, a: Asset, is: IntegrationStatu, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: update_experiment_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: update_experiment_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e   : experiment-set
    s   : session-set
    n   : ~exp-name-set
    eid : ~exp-id-set
    i   : institute-set
    d   : discipline-set
    r   : developer-set
    h   : hostinginfo-set
    a   : asset-set
    is  : integrationstatus-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: update_experiment_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The experiment details are updated.
#+END_SRC


** Update Institute
  :PROPERTIES:
  :CUSTOM_ID:  update_institute
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: update_institute_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: inst_name, iid: inst_id, i: Institute, a: Asset, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: update_institute_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: update_institute_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i   : institute-set
    s   : session-set
    n   : inst-name-set
    iid : ~inst-id-set
    a   : asset-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: update_institute_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The institute details are updated.
#+END_SRC


** Update Discipline
  :PROPERTIES:
  :CUSTOM_ID: update_discipline
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: update_discipline_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: disc_name, did: disc_id, d: Discipline, a: Asset, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: update_discipline_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: update_discipline_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d  : discipline-set
    s  : session-set
    n  : disc-name-set
    did: ~disc-id-set
    a  : asset-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: update_discipline_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The discipline details are updated.
#+END_SRC


** Update Developer
  :PROPERTIES:
  :CUSTOM_ID: update_developer
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: update_developer_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: name, e: email_id, r: Developer, i: Institute, d: Discipline, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: update_developer_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: update_developer_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r   : developer-set
    n   : name-set
    e   :~email-set
    i   : institute-set
    d   : discipline-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: update_developer_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    The developer details are updated.

#+END_SRC


** Update HostingInfo
  :PROPERTIES:
  :CUSTOM_ID: update_hostinginfo
  :END:
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: update_hostinginfo_parameters
  :END:
#+BEGIN_SRC spec :tangle spec.txt
   hs: hosting_status, hu: hosted_url, ho: hosted_on, h: HostingInfo , s: Session
   #+END_SRC
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: update_hostinginfo_actor_credentials
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: update_hostinginfo_referential_integrity
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    h  : hostinginfo-set
    s  : session-set
    hs : hosting-status-set
    hu : ~hosted-url-set
    ho : hosted-on-set

#+END_SRC
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: update_hostinginfo_effect
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    The HostingInfo details are updated.
#+END_SRC


** Update Asset
  :PROPERTIES:
  :CUSTOM_ID: update_asset
  :END:
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: update_asset_parameters
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    at: asset_type, ap: asset_path, a: Asset, s: Session
#+END_SRC
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: update_asset_actor_credentials
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: update_asset_referential_integrity
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    a : asset-set
    s : session-set
    at: asset-type-set
    ap: ~asset-path-set

#+END_SRC
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: update_asset_effect
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    The Asset details are updated.
#+END_SRC


** Delete Lab
  :PROPERTIES:
  :CUSTOM_ID: delete_lab
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_lab_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l: Lab, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_lab_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_lab_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    l : lab-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_lab_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    lab-set = lab-set - {l}

#+END_SRC


** Delete Experiment
  :PROPERTIES:
  :CUSTOM_ID: delete_experiment
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_experiment_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: Experiment, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_experiment_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_experiment_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e : experiment-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_experiment_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    experiment-set = experiment-set - {e}

#+END_SRC


** Delete Institute
  :PROPERTIES:
  :CUSTOM_ID: delete_institute
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_institute_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i: Institute, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_institute_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_institute_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    i : institute-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_institute_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    institute-set = institute-set - {i}

#+END_SRC


** Delete Discipline 
  :PROPERTIES:
  :CUSTOM_ID: delete_discipline
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_discipline_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d: Discipline, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_discipline_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_discipline_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    d : discipline-set
    s : session-set
#+END_SRC   

*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_discipline_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    discipline-set = discipline-set - {d}

#+END_SRC


** Delete Section
  :PROPERTIES:
  :CUSTOM_ID: delete_section
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_lab_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    sec: Section, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_section_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_section_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    sec : section-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_section_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    section-set = section-set - {sec}

#+END_SRC


** Delete Name
  :PROPERTIES:
  :CUSTOM_ID: delete_name
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_name_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n: Name, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_name_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_name_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    n : name-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_name_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    name-set = name-set - {n}

#+END_SRC


** Delete Email
  :PROPERTIES:
  :CUSTOM_ID: delete_email
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_email_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e: Email, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_email_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_email_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    e : email-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_email_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    email-set = email-set - {e}

#+END_SRC


** Delete Developer
  :PROPERTIES:
  :CUSTOM_ID: delete_developer
  :END: 
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_developer_parameters
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r: Developer, s: Session
#+END_SRC   
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_developer_actor_credentials
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC   
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_developer_referential_integrity
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    r : developer-set
    s : session-set

#+END_SRC   
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_developer_effect
  :END: 
#+BEGIN_SRC spec :tangle spec.txt
    developer-set = developer-set - {r}
#+END_SRC


** Delete HostingInfo
  :PROPERTIES:
  :CUSTOM_ID: delete_hostinginfo
  :END:
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_hostinginfo_parameters
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    h: HostingInfo, s: Session
#+END_SRC
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_hostinginfo_actor_credentials
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_hostinginfo_referential_integrity
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    h : hostinginfo-set
    s : session-set

#+END_SRC
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_hostinginfo_effect
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    hostinginfo-set = hostinginfo-set - {h}
    
#+END_SRC


** Delete Asset
  :PROPERTIES:
  :CUSTOM_ID: delete_asset
  :END:
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_asset_parameters
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    a: Asset, s: Session
#+END_SRC
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_asset_actor_credentials
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_asset_referential_integrity
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    a : asset-set
    s : session-set

#+END_SRC
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_asset_effect
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    asset-set = asset-set - {a}

#+END_SRC


** Delete IntegrationStatus
  :PROPERTIES:
  :CUSTOM_ID: delete_integrationstatus
  :END:
*** Parameters
  :PROPERTIES:
  :CUSTOM_ID: delete_integrationstatus_parameters
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    is: IntegrationStatus, s: Session
#+END_SRC
*** Actor credentials
  :PROPERTIES:
  :CUSTOM_ID: delete_integrationstatus_actor_credentials
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    s.key == system configured key
#+END_SRC
*** Referential Integrity
  :PROPERTIES:
  :CUSTOM_ID: delete_integrationstatus_referential_integrity
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    is : integrationstatus-set
    s : session-set

#+END_SRC
*** Effect
  :PROPERTIES:
  :CUSTOM_ID: delete_integrationstatus_effect
  :END:
#+BEGIN_SRC spec :tangle spec.txt
    integrationstatus-set = integrationstatus-set - {i}

#+END_SRC
