#+TITLE: Design of lab-data-service
#+AUTHOR: VLEAD
#+DATE: [2017-05-01 Friday]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction 
  The =design= of the =lab-data-service= is captured here.


* Application Programming Interface
  :PROPERTIES:
  :CUSTOM_ID: api
  :END: 

** Add Discipline
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /disciplines

  - Method :: POST

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE
{
   "dis_id": "cse",
   "dis_name": "Computer Science",
   "key": "defaultkey"
}
#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
    + Content: 
#+BEGIN_EXAMPLE
{
  "dis_id": "cse", 
  "dis_name": "Computer Science", 
  "id": 1
}

#+END_EXAMPLE

  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/disciplines][example url]]


** Add Institute
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /institutes

  - Method :: POST

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE
{
   "inst_id": "iiith",
   "inst_name": "IIIT Hyderabad",
   "key": "defaultkey"
}
#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
    + Content: 
#+BEGIN_EXAMPLE
{
  "id": 1, 
  "inst_id": "iiith", 
  "inst_name": "IIIT Hyderabad"
}

#+END_EXAMPLE

  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/institutes][example url]]

    
** Add sections
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /sections

  - Method :: POST

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE

{
  "key": "<key>",
  "name" : "Theory"
}

#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
    + Content: 
      {"status" : "successfully added records"}

  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/sections][example url]]


** Add Experiment
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments

  - Method :: POST

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE
{
  "exp_id": "exp9", 
  "exp_name": "arrays", 
  "key":"defaultkey",
  "overview": "overview", 
  "sections": ["Theory", "Procedure"]
}
#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
    + Content: 
#+BEGIN_EXAMPLE
{
  "exp_id": "exp9", 
  "exp_name": "arrays", 
  "id": 1, 
  "overview": "overview", 
  "sections": [
    {
      "id": 1, 
      "name": "Theory"
    }, 
    {
      "id": 2, 
      "name": "Procedure"
    }
  ]
}

#+END_EXAMPLE

  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/experiments][example url]]


** Add Lab
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs

  - Method :: POST

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE
{
  "experiments": ["exp9"], 
  "lab_id": "cse09", 
  "lab_name": "Data Structures", 
  "overview": "overview",
  "key": "defaultkey",
  "inst_id": "iiith",
  "dis_id": "cse"
}
#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
    + Content: 
#+BEGIN_EXAMPLE
{
  "discipline": {
    "dis_id": "cse", 
    "dis_name": "Computer Science", 
    "id": 1
  }, 
  "experiments": [
    {
      "exp_id": "exp9", 
      "exp_name": "arrays", 
      "id": 1, 
      "overview": "overview", 
      "sections": [
        {
          "id": 2, 
          "name": "Procedure"
        }, 
        {
          "id": 1, 
          "name": "Theory"
        }
      ]
    }
  ], 
  "id": 1, 
  "institute": {
    "id": 1, 
    "inst_id": "iiith", 
    "inst_name": "IIIT Hyderabad"
  }, 
  "lab_id": "cse09", 
  "lab_name": "Data Structures", 
  "overview": "overview"
}

#+END_EXAMPLE

  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs][example url]]


** Get all labs
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE
[
  {
    "discipline": {
      "dis_id": "cse",
      "id": 1,
      "dis_name": "Computer Science"
    },
    "lab_id": "cse09",
    "institute": {
      "inst_name": "IIIT Hyderabad",
      "id": 1,
      "inst_id": "iiith"
    },
    "overview": "overview",
    "lab_name": "Data Structures",
    "experiments": [
      {
        "overview": "overview",
        "exp_name": "arrays",
        "sections": [
          {
            "name": "Procedure",
            "id": 2
          },
          {
            "name": "Theory",
            "id": 1
          }
        ],
        "id": 1,
        "exp_id": "exp9"
      }
    ],
    "id": 1
  }
]
#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs][example url]]


** Get all experiments
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE

[
  {
    "overview": "overview",
    "exp_name": "arrays",
    "sections": [
      {
        "name": "Procedure",
        "id": 2
      },
      {
        "name": "Theory",
        "id": 1
      }
    ],
    "id": 1,
    "exp_id": "exp9"
  }
]
#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/experiments][example url]]


** Get all Sections
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /sections

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE
[
  {
    "overview": "overview",
    "exp_name": "arrays",
    "sections": [
      {
        "name": "Procedure",
        "id": 2
      },
      {
        "name": "Theory",
        "id": 1
      }
    ],
    "id": 1,
    "exp_id": "exp9"
  }
]
#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/sections][example url]]


** Get all Disciplines
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /disciplines

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE
[
  {
    "overview": "overview",
    "exp_name": "arrays",
    "sections": [
      {
        "name": "Procedure",
        "id": 2
      },
      {
        "name": "Theory",
        "id": 1
      }
    ],
    "id": 1,
    "exp_id": "exp9"
  }
]
#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/disciplines][example url]]


** Get all Institutes
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /institutes

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE
[{"inst_name": "IIIT Hyderabad", "id": 1, "inst_id": "iiith"}]
#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/institutes][example url]]

    
** Update lab by labid
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs/lab_id=<lab_id>

  - Method :: PUT

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE
{
  "lab_name": "Databases", 
  "overview": "overview of Databases",
  "key": "defaultkey"
}
#+END_EXAMPLE
  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "discipline": {
    "dis_id": "cse", 
    "dis_name": "Computer Science", 
    "id": 1
  }, 
  "experiments": [
    {
      "exp_id": "exp9", 
      "exp_name": "arrays", 
      "id": 1, 
      "overview": "overview", 
      "sections": [
        {
          "id": 2, 
          "name": "Procedure"
        }, 
        {
          "id": 1, 
          "name": "Theory"
        }
      ]
    }
  ], 
  "id": 1, 
  "institute": {
    "id": 1, 
    "inst_id": "iiith", 
    "inst_name": "IIIT Hyderabad"
  }, 
  "lab_id": "cse09", 
  "lab_name": "Databases", 
  "overview": "overview of Databases"
}

#+END_EXAMPLE

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    http://localhost:5000/labs?lab_id=cse09


** Update experiment by expid
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments/exp_id=<exp_id>

  - Method :: PUT

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE
{
  "exp_name": "2D arrays", 
  "key":"defaultkey",
  "overview": "2D Arrays overview"
}

#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "exp_id": "exp9", 
  "exp_name": "2D arrays", 
  "id": 1, 
  "overview": "2D Arrays overview", 
  "sections": [
    {
      "id": 2, 
      "name": "Procedure"
    }, 
    {
      "id": 1, 
      "name": "Theory"
    }
  ]
}

#+END_EXAMPLE
    
  - Error Response:
    + Contents :
      {"status" : "error"}
      
  - Example:
    http://localhost:5000/experiments?exp_id=exp9


    
** Update disciplines by disid
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /disciplines/dis_id=<dis_id>

  - Method :: PUT

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE
{
"dis_name": "Computer Science and Engineering",
  "key": "defaultkey"
}
#+END_EXAMPLE
  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
 {
  "dis_id": "cse", 
  "dis_name": "Computer Science and Engineering", 
  "id": 1
}

#+END_EXAMPLE

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    http://localhost:5000/disciplines?dis_id=cse


** Update institutes by instid
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /institutes/inst_id=<inst_id>

  - Method :: PUT

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE
{
"inst_name": "IIIT H",
  "key": "defaultkey"
}

#+END_EXAMPLE
  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "id": 1, 
  "inst_id": "iiith", 
  "inst_name": "IIIT H"
}

#+END_EXAMPLE

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    http://localhost:5000/institutes?inst_id=iiith


** Update section by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /sections/<id>

  - Method :: PUT

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE

{
  "key" : "<key",
  "name" : "Quiz"
}


#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "id": 1, 
  "name": "Quiz"
}
#+END_EXAMPLE
    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/sections/1][example url]]



** Delete lab by lab_id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs?lab_id=<lab_id>&key=<key>

  - Method :: DELETE

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "status": "success"
}

#+END_EXAMPLE
    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    http://localhost:5000/labs?lab_id=cse09&key=defaultkey


** Delete experiment by exp_id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments?exp_id=<exp_id>&key=<key>

  - Method :: DELETE

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "status": "success"
}

#+END_EXAMPLE
    
  - Error Response:
    + Contents :
      {"status" : "error"}
      
  - Example:
    [[http://localhost:5000/experiments/exp_id%3Dchem12&key%3Ddefaultkey][example url]]


** Delete discipline by dis_id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /disciplines?disc_id=<dis_id>&key=<key>

  - Method :: DELETE

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "status": "success"
}

#+END_EXAMPLE
    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    http://localhost:5000/disciplines?dis_id=cse&key=defaultkey


** Delete institute by inst_id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /institutes?inst_id=<inst_id>&key=<key>

  - Method :: DELETE

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "status": "success"
}

#+END_EXAMPLE
    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    http://localhost:5000/institutes?inst_id=iitd&key=defaultkey


** Delete section by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /sections/<id>

  - Method :: DELETE

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
        { "status" : "success" }
    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/section/2][example url]]


** Get lab by lab_name
  :PROPERTIES:
  :CUSTOM_ID: get_lab_by_lab_name
  :END:    
  - URL :: /labs/<lab_name>

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "experiments": [
    {
      "exp_id": "e99848", 
      "exp_name": "Parallel and distributed processing", 
      "id": 7, 
      "overview": "This deals with eiciting how parallel and distributed processing is done", 
      "sections": []
    }
  ], 
  "id": 2, 
  "lab_id": "cse06", 
  "lab_name": "Computer Programming", 
  "overview": "This lab deals with computer programming"
}

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs/Data Structures][example url]]


** Get experiment resource map
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /exp_resource_map/exp_id=<exp-id>

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response

    + Status_Code: 200
      + Contents :
           
#+BEGIN_EXAMPLE
Not yet implememented

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
      {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/exp_resource_map/exp_id%3Dcse02][example url]]


** Get lab resource map
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /lab_resource_map/lab_id=<lab-id>

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE
Not yet implemented

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
      {"status" : "error"}
      
  - Example:
    [[http://localhost:5000/lab_resource_map/lab_id%3Dcse03][example url]]


* Specification
  Every experiment and a lab has a specification. The specification provides a
  unique ID, name, contents of an experiment and other meta information of
  either a lab or experiment. This information includes: developer details, the
  organization a lab belongs to, discipline details, hosting information
  i.e. on which platform the lab/experiments are hosted, integration status of
  labs and the assets associated with a lab/experiment. This specification is
  different from the deployment specification of an experiment.

** Experiment Specification
   An experiment is a basic functional unit of virtual labs. An experiment is a
   combination of static content and simulation. Each experiment is identified
   by a unique id, name, institute, discipline, developer, hosting information,
   integration status, assets etc.

#+begin_src
{
  "experiment": {
    "id": "e99847",
    "name": "Parallel and distributed processing",
    "discipline_id": "CSE",
    "institute_id": "IIITH",
    "developers": [
      {
        "name": "Dinesh Malviya",
        "email": "xyz@gmail.com"
      },
      {
        "name": "Ashish Ahuja",
        "email": "abc@gmail.com"
      }
    ],
    "hosting_info": [
      {
        "hosting_status": "hosted",
        "hosted_on": "cloud",
        "hosted_url": "http://cse14-iiith.vlabs.ac.in"
      },
      {
        "hosting_status": "hosted",
        "hosted_on": "college-cloud",
        "hosted_url": "http://cse14-iiith.ac.in"
      }
    ],
    "integration_level": "4",
    "assets": [
      {
        "asset_type": "image",
        "path": [
          "vlabs.ac.in/images/static/logo.png"
        ]
      },
      {
        "asset_type": "video",
        "path": [
          "vlabs.ac.in/video/abc.mkv"
        ]
      }
    ],
    "sections": [
      "Introduction",
      "Objective",
      "Tutorial",
      "Illustration",
      "Procedure",
      "Experiment",
      "Observations",
      "Assignment",
      "References"
    ]
  }
}
#+end_src 

** Lab Specification
   A lab is collation of experiments. A lab is identified by a unique id. The
   lab specification contains this identifier along with name, name of the
   organization, discipline, developer, hosting information, integration
   status, assets etc. The experiments in a lab are specified by including
   their respective ids.
#+begin_src
{"lab": {"id": "cse02", 
                "name": "Computer Programming",
                "discipline_id": "CSE",
                "institute_id": "IIITH",
                "developers": [{"name":"Dinesh Malviya", "email": "xyz@gmail.com"},
                               {"name": "Ashish Ahuja", "email":"abc@gmail.com"}],
                "hosting_info": [{"hosting_status": "hosted", "hosted_on": "cloud", "hosted_url": "http://cse14-iiith.vlabs.ac.in"},
                                 {"hosting_status": "hosted", "hosted_on": "college-cloud", "hosted_url": "http://cse14-iiith.ac.in"}],
                "integration_level": "4",
                "assets": [{"asset_type": "Images", "path": "vlabs.ac.in/images/static/logo.png"},
                           {"asset_type": "Videos", "path": "vlabs.ac.in/video/abc.mkv"}],
                "overview": "This lab deals with computer programming",
                "experiments": [e100, e200, ....]
              }
}
#+end_src

** Institute Specification
   Each =Institute= is identified by a unique =inst_id=. 
#+BEGIN_SRC 
{
"inst_id": "IIITH",
"inst_name": "IIIT Hyderabad"
}
#+END_SRC
** Discipline Specification
   Each =Discipline= is identified by a unique =dis_id=. 
#+BEGIN_SRC 
{
  "dis_id": "CSE", 
  "dis_name": "Computer Science and Engineering"
}

#+END_SRC


* Design diagram
  :PROPERTIES:
  :CUSTOM_ID: design_diagram
  :END:    

#+BEGIN_HTML
<img src="https://docs.google.com/drawings/d/e/2PACX-1vQ-WiohgmhaseluocCU0TBOoIUSWctv6raQ03gPO_-jhRkgtQbxH2DX0924ux3O7Hfz3zwKGJnt7r1Z/pub?w=960&h=720">
<p align="center"> lab data service design diagram </p>
#+END_HTML

 [[https://docs.google.com/drawings/d/1TAaHpf0UiCLvLRP_XfBBQki7pU624oWXRduxyz6e1NA/edit?ts=58415ec0][click here]] to edit the diagram
** Process
*** Get the lab's meta data
   :PROPERTIES:
   :CUSTOM_ID: lab_meta_data
   :END: 

   - Get all the labs meta data which includes lab id, experiment id,
     institutes, disciplines and developers details.

*** Construct lab spec with lab's meta data in json format 
   :PROPERTIES:
   :CUSTOM_ID: construct_lab_spec
   :END: 
   
   - Lab spec should be filled up with consistant naming convention of
     lab id, experiment id, institutes, disciplines and developers
     details in =json= format

*** Version controll lab spec file 
   :PROPERTIES:
   :CUSTOM_ID: version_lab_specs
   :END: 
   
   - All the lab spec files has to be checked into the single git
     repository.

*** Parse lab spec files checked into git repo 
   :PROPERTIES:
   :CUSTOM_ID: parse_lab_specs
   :END: 

   - A =web-hook= from Github repository will invoke the
     =lab-data-service= when changes made to lab specs.
   - =lab-data-service= has to parse the lab spec files and stored the
     data into the database.
   
*** All lab spec files in git repo are read only  
   :PROPERTIES:
   :CUSTOM_ID: lab_spec_read_only
   :END: 

   - Only admin or group of authorized users of git repository has
     access to modify the lab spec files.

