#+TITLE: Design of lab-data-service
#+AUTHOR: VLEAD
#+DATE: [2017-05-01 Friday]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction 
  The =design= of the =lab-data-service= is captured here.


* Application Programming Interface
  :PROPERTIES:
  :CUSTOM_ID: api
  :END: 

** Save exp spec data
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments

  - Method :: POST

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE

{
  "exp_id": "e99847",
  "key" : "<key>",
  "exp_name": "Parallel and distributed processing",
  "overview": "This deals with eiciting how parallel and distributed processing is done",
  "sections": [
    {
      "name": "Introduction"
    },
    {
      "name": "Objective"
    },
    {
      "name": "Tutorial"
    },
    {
      "name": "Illustration"
    },
    {
      "name": "Procedure"
    },
    {
      "name": "Experiment"
    },
    {
      "name": "Observations"
    },
    {
      "name": "Assignment"
    },
    {
      "name": "References"
    }
  ]
}

#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
    + Content: 
              {"status" : "successfully added records"}

  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/save_exp_spec_data][example url]]


** Get all experiments
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE
[
  {
    "overview": "overview",
    "exp_name": "arrays",
    "sections": [
      {
        "name": "Theory",
        "id": 1
      }
    ],
    "id": 2,
    "exp_id": "cse01"
  },
  {
    "overview": "overview",
    "exp_name": "arrays",
    "sections": [
      {
        "name": "Theory",
        "id": 1
      }
    ],
    "id": 4,
    "exp_id": "cse02"
  },
  {
    "overview": "This deals with eiciting how parallel and distributed processing is done",
    "exp_name": "Parallel and distributed processing",
    "sections": [
      {
        "name": "Introduction",
        "id": 2
      },
      {
        "name": "Objective",
        "id": 3
      }
     ],
    "id": 5,
    "exp_id": "e99847"
  },
  {
    "overview": "This deals with eiciting how parallel and distributed processing is done",
    "exp_name": "Parallel and distributed processing",
    "sections": [],
    "id": 7,
    "exp_id": "e99848"
  }
]

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/experiments][example url]]

    
** Update experiment by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments/<id>

  - Method :: PUT

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE

  {
    "exp_name": "arrays",
    "overview": "this is about arrays exp",
    "exp_id": "cse02",
    "key" : "<key>"
  }

#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
      + Contents :
                {"status" : "successfully updated records"}
    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/experiments/2][example url]]


    
** Get experiment by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments/<id>

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "exp_id": "cse01", 
  "exp_name": "arrays", 
  "id": 2, 
  "overview": "overview", 
  "sections": [
    {
      "id": 1, 
      "name": "Theory"
    }
  ]
}

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/experiments/2][example url]]


** Delete exp by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /experiments/<id>

  - Method :: DELETE

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
                {"status" : "successfully deleted records"}
    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/experiments/2][example url]]


** Save lab spec data
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs

  - Method :: POST

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE

{
  "lab_id": "cse02",
  "key": "<key>",
  "lab_name": "Computer Programming",
  "overview": "This lab deals with computer programming",
  "experiments": [
    {
      "exp_id": "e99847",
      "exp_name": "Parallel and distributed processing",
      "overview": "This deals with eiciting how parallel and distributed processing is done",
      "sections": [
        {
          "name": "Introduction"
        },
        {
          "name": "Objective"
        }
      ]
    }
  ]
}

#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
    + Content: 
              {"status" : "successfully added records"}

  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/save_lab_spec_data][example url]]


** Get lab by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs/<id>

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "experiments": [
    {
      "exp_id": "e99848", 
      "exp_name": "Parallel and distributed processing", 
      "id": 7, 
      "overview": "This deals with eiciting how parallel and distributed processing is done", 
      "sections": []
    }
  ], 
  "id": 2, 
  "lab_id": "cse06", 
  "lab_name": "Computer Programming", 
  "overview": "This lab deals with computer programming"
}

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs/2][example url]]


** Get lab by lab_name
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs/<lab_name>

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
#+BEGIN_EXAMPLE
{
  "experiments": [
    {
      "exp_id": "e99848", 
      "exp_name": "Parallel and distributed processing", 
      "id": 7, 
      "overview": "This deals with eiciting how parallel and distributed processing is done", 
      "sections": []
    }
  ], 
  "id": 2, 
  "lab_id": "cse06", 
  "lab_name": "Computer Programming", 
  "overview": "This lab deals with computer programming"
}

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs/Data Structures][example url]]


** Update lab by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs/<id>

  - Method :: PUT

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE

{
  "key" : "<key",
  "lab_id": "cse06", 
  "lab_name": "Computer Programming", 
  "overview": "This lab deals with computer programming"
}


#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
      + Contents :
                {"status" : "success"}
    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs/2][example url]]

    
** Get all labs
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE
[
  {
    "lab_name": "Computer Programming",
    "experiments": [],
    "overview": "This lab deals with computer programming",
    "id": 1,
    "lab_id": "cse02"
  },
  {
    "lab_name": "Computer Programming",
    "experiments": [
      {
        "overview": "This deals with eiciting how parallel and distributed processing is done",
        "exp_name": "Parallel and distributed processing",
        "sections": [],
        "id": 7,
        "exp_id": "e99848"
      }
    ],
    "overview": "This lab deals with computer programming",
    "id": 2,
    "lab_id": "cse06"
  }
]

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs][example url]]


** Delete lab by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /labs/<id>

  - Method :: DELETE

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
                 { "status" : "success" }
    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/experiments/2][example url]]


** Add sections
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /sections

  - Method :: POST

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE

{
  "key": "<key>",
  "name" : "Theory"
}

#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
    + Content: 
              {"status" : "successfully added records"}

  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/save_lab_spec_data][example url]]


** Get all sections
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /sections

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

#+BEGIN_EXAMPLE

[
  {
    "name": "Theory",
    "id": 1
  },
  {
    "name": "Introduction",
    "id": 2
  },
  {
    "name": "Objective",
    "id": 3
  },
  {
    "name": "Tutorial",
    "id": 4
  },
  {
    "name": "Experiment",
    "id": 7
  },
  {
    "name": "Observations",
    "id": 8
  }
]

#+END_EXAMPLE	       



  - Success Response
    + Status_Code: 200
      + Contents :
         {"status" : "success"}
    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs][example url]]



** Update section by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /sections/<id>

  - Method :: PUT

  - URL Params ::  None

  - Payload :: 
#+BEGIN_EXAMPLE

{
  "key" : "<key",
  "name" : "Quiz"
}


#+END_EXAMPLE	       

  - Success Response
    + Status_Code: 200
      + Contents :
                {"status" : "success"}
    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/labs/2][example url]]




** Delete section by id
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /sections/<id>

  - Method :: DELETE

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :
                 { "status" : "success" }
    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/experiments/2][example url]]


** Get experiment resource map
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /exp-resource-map/<exp-id>

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response


    + Status_Code: 200
      + Contents :
           
#+BEGIN_EXAMPLE
Not yet implemented

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/save_lab_spec_data][example url]]


** Get exp resource map
  :PROPERTIES:
  :CUSTOM_ID: save_lab_specs
  :END:    
  - URL :: /exp-resource-maps/<exp-id>

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Success Response
    + Status_Code: 200
      + Contents :

#+BEGIN_EXAMPLE
Not yet implemented

#+END_EXAMPLE	       

    
  - Error Response:
    + Contents :
                {"status" : "error"}
    
  - Example:
    [[http://localhost:5000/save_lab_spec_data][example url]]


* Design diagram
  :PROPERTIES:
  :CUSTOM_ID: design_diagram
  :END:    

#+BEGIN_HTML
<img src="https://docs.google.com/drawings/d/e/2PACX-1vQ-WiohgmhaseluocCU0TBOoIUSWctv6raQ03gPO_-jhRkgtQbxH2DX0924ux3O7Hfz3zwKGJnt7r1Z/pub?w=960&h=720">
<p align="center"> lab data service design diagram </p>
#+END_HTML

  To edit the feedback relations image [[https://docs.google.com/drawings/d/1TAaHpf0UiCLvLRP_XfBBQki7pU624oWXRduxyz6e1NA/edit?ts=58415ec0][click here]]
** Process
*** Get the lab's meta data
   :PROPERTIES:
   :CUSTOM_ID: lab_meta_data
   :END: 

   - Get all the labs meta data which includes lab id, experiment id,
     institutes, disciplines and developers details.

*** Construct lab spec with lab's meta data in json format 
   :PROPERTIES:
   :CUSTOM_ID: construct_lab_spec
   :END: 
   
   - Lab spec should be filled up with consistant naming convention of
     lab id, experiment id, institutes, disciplines and developers
     details in =json= format

*** Version controll lab spec file 
   :PROPERTIES:
   :CUSTOM_ID: version_lab_specs
   :END: 
   
   - All the lab spec files has to be checked into the single git repository.

*** Parse lab spec files checked into git repo 
   :PROPERTIES:
   :CUSTOM_ID: parse_lab_specs
   :END: 

   - A =web-hook= from Github repository will invoke the
     =lab-data-service= when changes made to lab specs.
   - =lab-data-service= has to parse the lab spec files and stored the
     data into the database.
   
*** All lab spec files in git repo are read only  
   :PROPERTIES:
   :CUSTOM_ID: lab_spec_read_only
   :END: 

   - Only admin or group of authorized users of git repository has
     access to modify the lab spec files.

